export const MOCK_BOOK_OWNER_DATA: any[] = [
  {
    id: 1,
    book_store_name: 'Hansen Group',
    book_owner_name: 'Melodie Lamden',
    email: 'mlamden0@networksolutions.com',
    password: 'y|C*vOm=5S',
    phone_number: '+86 264 690 0547',
    role_id: 2,
  },
  {
    id: 2,
    book_store_name: 'Lockman-Quitzon',
    book_owner_name: 'Josiah Cordel',
    email: 'jcordel1@merriam-webster.com',
    password: 'jnZ`PZg/',
    phone_number: '+7 758 870 3441',
    role_id: 2,
  },
  {
    id: 3,
    book_store_name: 'Sipes LLC',
    book_owner_name: 'Lora Coneybeare',
    email: 'lconeybeare2@wsj.com',
    password: 'z!8xg<vHZ>',
    phone_number: '+55 225 143 2844',
    role_id: 2,
  },
  {
    id: 4,
    book_store_name: 'Satterfield, Hintz and Schultz',
    book_owner_name: 'Zandra Ansley',
    email: 'zansley3@angelfire.com',
    password: 'o#r!5"Nx>ERf',
    phone_number: '+63 669 484 3323',
    role_id: 2,
  },
  {
    id: 5,
    book_store_name: 'Dicki, Lehner and Paucek',
    book_owner_name: 'Harlene Ayer',
    email: 'hayer4@1und1.de',
    password: 'uFeqCQs=Z4',
    phone_number: '+964 333 873 9851',
    role_id: 2,
  },
  {
    id: 6,
    book_store_name: 'Welch LLC',
    book_owner_name: 'Mae Thickpenny',
    email: 'mthickpenny5@mapy.cz',
    password: 'oTASNmONBa',
    phone_number: '+380 699 290 6626',
    role_id: 2,
  },
  {
    id: 7,
    book_store_name: 'Hirthe, Wiegand and Hammes',
    book_owner_name: 'Katheryn Peete',
    email: 'kpeete6@mozilla.org',
    password: 'oo0C}.i)p8`F',
    phone_number: '+254 114 874 8465',
    role_id: 2,
  },
  {
    id: 8,
    book_store_name: 'Grimes-Champlin',
    book_owner_name: 'Jocelyn Mayhou',
    email: 'jmayhou7@wiley.com',
    password: 'gTSV7sbx',
    phone_number: '+31 698 818 4488',
    role_id: 2,
  },
  {
    id: 9,
    book_store_name: 'Langosh, Kuhlman and Spinka',
    book_owner_name: 'Samson Firmage',
    email: 'sfirmage8@drupal.org',
    password: 'cmE1yIUi%QB5',
    phone_number: '+48 785 362 6381',
    role_id: 2,
  },
  {
    id: 10,
    book_store_name: 'Brekke-Macejkovic',
    book_owner_name: 'Jacky Mattock',
    email: 'jmattock9@livejournal.com',
    password: 'p4rwQ0%7|',
    phone_number: '+48 134 863 3448',
    role_id: 2,
  },
  {
    id: 11,
    book_store_name: 'Wiegand LLC',
    book_owner_name: 'Elvera Sisland',
    email: 'esislanda@networksolutions.com',
    password: "w'`nDUl",
    phone_number: '+1 402 520 4049',
    role_id: 2,
  },
  {
    id: 12,
    book_store_name: 'Glover-Krajcik',
    book_owner_name: 'Aryn Standish',
    email: 'astandishb@squidoo.com',
    password: 'rd34pd?o4',
    phone_number: '+62 757 251 0442',
    role_id: 2,
  },
];
